# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsUse < Formula
  desc "Switch AWS SSO accounts/roles fast across multiple SSO sessions"
  homepage "https://github.com/dbaggott/aws-use"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.1/aws-use_darwin_amd64.tar.gz"
      sha256 "5bf3443bb347c4a2311d003880ff87ee30a4d9e035f3152d072ef1856280b88c"

      define_method(:install) do
        bin.install "aws-use"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.1/aws-use_darwin_arm64.tar.gz"
      sha256 "d8aa548da67ff13648828e3f3b7995c75b024873645f187cb28767d317d5cc1f"

      define_method(:install) do
        bin.install "aws-use"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.1/aws-use_linux_amd64.tar.gz"
      sha256 "15e015a37cfb6f5fb5b49715de9bfadf777d9f14dd4c9a83f9a474c80516717f"
      define_method(:install) do
        bin.install "aws-use"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.1/aws-use_linux_arm64.tar.gz"
      sha256 "be51721065fc56ee447b4d9a3f254509ce40a2bb520e6c5a432131e41db50b67"
      define_method(:install) do
        bin.install "aws-use"
      end
    end
  end

  def caveats
    <<~EOS
      aws-use switches your shell's AWS profile, so it needs a shell hook.
      Add this to your shell startup file, then restart your shell:

        ~/.zshrc or ~/.bashrc:  eval "$(aws-use shellenv)"

      Without the hook, `aws-use` prints the profile it picked but can't set
      AWS_PROFILE in your current shell.
    EOS
  end

  test do
    system "#{bin}/aws-use", "version"
  end
end
