# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsUse < Formula
  desc "Switch AWS SSO accounts/roles fast across multiple SSO sessions"
  homepage "https://github.com/dbaggott/aws-use"
  version "0.1.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.5/aws-use_darwin_amd64.tar.gz"
      sha256 "b6741dbb7e691de2f041dd26d5f41fe3ff2e5be922c0d1124c742cef438dcf22"

      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.5/aws-use_darwin_arm64.tar.gz"
      sha256 "845128eccd3ea111b229dfd93c253d664a7f129061da0a024e613e901695ad3c"

      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.5/aws-use_linux_amd64.tar.gz"
      sha256 "9cd8644c9860a1caf3c10a005345f200192ceaae80eddc0670e0683392dcbc87"
      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.5/aws-use_linux_arm64.tar.gz"
      sha256 "8672249dea39672335aa0c73cbded5cfab993b6a765aa4af7f8230bfdd5f836a"
      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      aws-use switches your shell's AWS profile, so it needs a shell hook.
      Add this to your shell startup file, then restart your shell:

        ~/.zshrc or ~/.bashrc:  eval "$(aws-use shellenv)"

      Without the hook, `aws-use` prints the profile it picked but can't set
      AWS_PROFILE in your current shell.
    EOS
  end

  test do
    system "#{bin}/aws-use", "version"
  end
end
