# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AwsUse < Formula
  desc "Switch AWS SSO accounts/roles fast across multiple SSO sessions"
  homepage "https://github.com/dbaggott/aws-use"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.2/aws-use_darwin_amd64.tar.gz"
      sha256 "860ce4c0d6907072ec29b5b18efe08d10248fc2e1729ec62cf65b2bc94b21934"

      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.2/aws-use_darwin_arm64.tar.gz"
      sha256 "bfbec0b9daca5c9f797e45c8cfbc8bc0fa1eed62c3783807b3554c4f75467692"

      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.2/aws-use_linux_amd64.tar.gz"
      sha256 "671e55a04c48c8cf4c424e8f3d599d2ea40224a77f4f373a83946a1db96dbab0"
      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dbaggott/aws-use/releases/download/v0.1.2/aws-use_linux_arm64.tar.gz"
      sha256 "5276abaa7d4710d7135cd6d4e33ea4b2b25269f114a1827e41da49cc3020584f"
      define_method(:install) do
        bin.install "aws-use"
        generate_completions_from_executable(bin/"aws-use", "completion")
      end
    end
  end

  def caveats
    <<~EOS
      aws-use switches your shell's AWS profile, so it needs a shell hook.
      Add this to your shell startup file, then restart your shell:

        ~/.zshrc or ~/.bashrc:  eval "$(aws-use shellenv)"

      Without the hook, `aws-use` prints the profile it picked but can't set
      AWS_PROFILE in your current shell.
    EOS
  end

  test do
    system "#{bin}/aws-use", "version"
  end
end
